project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - Network_analysis.qmd

website:
  title: "Augmentum_eDNA_metabarcoding"
  navbar: false

execute:
  freeze: auto
  cache: true